ngrok:
  path: /root/ngrok/ngrok
#  path: /Volumes/Data/tools/ngrok
  log_path: /root/ngrok/ngrok.log
  git:
    username: xsi640
    password: 830128suyang
    url: https://gitee.com/xsi640/ngrok-to-git.git
    fileName: ng

